### 1.) Python Numpy :-

🔶 NumPy (Numerical Python) is a powerful open-source "Python library" used primarily for "numerical computing". 

🔶 It provides support for "large, multi-dimensional arrays" and matrices, along with a collection of mathematical 
   functions to operate on these arrays efficiently.

### 2.) Import Numpy Package as np :-

In [1]:
import numpy as np

### 3.) Create an Empty Array of 20, 0's & Replace The 4th Object With The Number 5 :-

In [2]:
a = np.zeros(20)
a[3] = 5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

### 4.) Create an Array of 20, 1's & Store It As a Variable Named array_master :-

* **[ Copy the same array into another variable named array_copy() ]**

In [3]:
array_master = np.ones(20)
array_copy = array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

❌

In [4]:
array_master = np.ones(20)
array_copy = array_master      
array_copy                   

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

* **Note :**

      -> [ This does not create a new array. Instead, array_copy is just another reference (alias) to the same
           array as array_master.
           Any changes made to array_copy will affect array_master, because both point to the same memory ]

### 5.) Create An Array Containing 30, 1's & Broadcast All The One's To The Value 100 :-

In [5]:
array = np.ones(30)
array[ : ] = 100
array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

* **Note :**

      -> [ The colon : is called a "slice operator" in Python and NumPy. It means, select all elements of the array ]

### 6.) Create An Array Of Integers Storing From 21 Until 31 & Name It As array_1 :-
###        Create An Array Of Integers Storing From 11 Until 21 & Name It As array_2 :-

* **[ Calculate the difference between array_1 & array_2 ]**

In [6]:
array_1 = np.arange( 21,32 )
array_2 = np.arange( 11,22 )

array_1 - array_2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

* **Note :**

      -> [ The function np.arange(start, stop) creates a 1D array of numbers, starting from start and stopping 
           before stop, with a default step size of 1 ]

### 7.) Create An Array Of All Even Integers From 2  to 10 & Name It a1 :-
###      Create An Array Of All Even Integers From 22 to 30 & Name It a2 :-

* **[ Use the 2 arrays as rows & create a matrix( Hint - Use "stack" function from numpy )]**

In [7]:
a1 = np.arange( 2,11,2 )
a2 = np.arange( 22,31,2 )

np.stack(( a1,a2 ))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

* **[ Use the 2 arrays as columns & create a matrix( Hint - Use column_stack function from numpy )]**

In [8]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

### 8.) Create a 5x6 Matrix With Values Ranging From 0 to 29 & Retrive The Value Interesecting at 2nd Row & 3rd  Column :-

In [9]:
array_matrix = np.arange(30).reshape(5,6)
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
array_matrix[1,2]

8

### 9.) Create An Identity Matrix, Shape Of 10x10 & Replace The 0's With The Value 21 :-

* **Identity Matrix :**

🔶 An identity matrix is a "square matrix". With same number of rows and columns.

🔶 Where, all diagonal elements are 1 & all other elements are 0.

🔶 In an identity matrix, the diagonal values are always 1.

In [11]:
arr = np.eye(10)
arr[ arr == 0 ] = 2
arr

array([[1., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 1., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 1., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 1., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 1., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 1., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 1., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 1.]])

* **Note :**

      -> [ The function np.eye(10) creates a 2D identity matrix of shape (10, 10) ]
      -> [ arr[ arr == 0 ] = 2 : Find all elements in arr that are equal to 0 and replace them with 2 ]

### 10.) Use Numpy To Generate a Random Set Of 10 Numbers Between 0 & 1 :-

* **[ Display a boolean array output where all value > 0.2 are True, rest are marked as False ]**

In [14]:
arr = np.random.rand(10)
arr

array([0.63457813, 0.95852294, 0.66467199, 0.61994858, 0.30145019,
       0.38796845, 0.46182258, 0.78398368, 0.27416679, 0.23642613])

In [15]:
arr > 0.2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

* **Note :**

      -> [ np.random.rand(10) generates an array of 10 random numbers ]
      -> [ These numbers are drawn from a "uniform distribution" over the interval [0, 1).
           That means each number will be ≥ 0 and < 1 ]
      -> [ The shape of the output array depends on the arguments you give. Here, 10 means a 1D 
           array with 10 elements ]

### 11.) Uniform Distribution :-

🔶 A uniform distribution is a type of "probability distribution" in which all outcomes are equally likely within a given 
   range. Every number within the specified range has the same probability of being selected. The probability is spread evenly 
   across the range.

🔶 A uniform distribution is not always between 0 and 1 — that's just the "default range" used in functions like  
   np.random.rand().

### 12.) Use Numpy to Generate An Array Matrix of 5x2 Random Numbers Sampled From a Standard Normal Distribution :-

In [16]:
np.random.randn(5,2)

array([[ 1.46103754,  0.00346311],
       [ 1.16050106, -0.40345311],
       [ 0.24202835, -1.05587056],
       [-0.98726739,  1.77967535],
       [-0.14189038, -0.65530615]])

### 13.) What Is The Difference Between random.rand() & random.randn() :-

🔶 **np.random.rand() :**

    Uniform distribution over [0, 1)
    All values between 0 and 1 are equally likely.
    The distribution is flat.
    
🔶 **np.random.randn() :**

    Standard normal distribution, also called "Gaussian or bell curve".
    Mean = 0.
    Standard deviation = 1.
    Most values are around 0, fewer as you go farther from 0.
    The distribution is bell-shaped.
    Values can be anything from -∞ to +∞, but. Most values lie in the range -3 to +3, 
    because it uses a "Standard Normal Distribution"(mean = 0, std = 1).

### 14.) Create an Array Of 30 Linearly Spaced Points Between 0 & 100 :-

In [17]:
np.linspace( 0,100,30 )

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

# NumPy Indexing & Selections


### 15.) Using The Below Given Matrix & Generate The Output For The Below Questions :-

In [19]:
simple_matrix = np.arange( 1,101 ).reshape( 10,10 )
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

* **Retrieve the last 2 rows & first 3 column values of the above matrix using index & selection technique :**

In [20]:
simple_matrix[ 8:, 0:3 ]

array([[81, 82, 83],
       [91, 92, 93]])

* **Retrieve the value 55 from the above matrix using index & selection technique :**

In [22]:
simple_matrix[ 5,4 ]

55

* **Retrieve the values from the 3rd column in the above matrix :**

In [24]:
simple_matrix[ :, 2 ]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

* **Retrieve the values from the 4th row in the above matrix :**

In [25]:
simple_matrix[ 3,: ]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [26]:
simple_matrix[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

* **Retrieve values from the 2nd & 4th rows in the above matrix :**

In [27]:
simple_matrix[ (1,3),: ]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

* **Calculate sum of all the values in the matrix :**

In [30]:
simple_matrix.sum()

5050

* **Calculate standard deviation of all the values in the matrix :**

In [31]:
simple_matrix.std()

28.86607004772212

* **Calculate the variance of all values in the matrix :**

In [32]:
simple_matrix.var()

833.25

* **Calculate the mean of all values in the matrix :**

In [33]:
simple_matrix.mean()

50.5

* **Retrieve the largest number from the matrix :**

In [34]:
simple_matrix.max()

100

* **Retrieve the smallest number from the matrix :**

In [35]:
simple_matrix.min()

1

### 16.) Standard Deviation :-

🔶 Standard deviation measures "how spread out the numbers" in a dataset are around the mean or average.

🔶 If the numbers are close to the mean, standard deviation is small.

🔶 If the numbers are widely spread, standard deviation is large.


* **Example :**

For this data: [5, 5, 5, 5, 5]

Mean = 5

All numbers are same as mean → Standard deviation = 0


For this data: [1, 5, 9]

Mean = 5

Numbers are spread around 5 → Standard deviation > 0

### 17.) Variance :-

🔶 Variance measures the "average squared distance" of each value from the mean. It tells you how spread out the values are.

* **Formula :**

                            n
             variance = 1/n ∑ ( xi - μ)^2
                           i=1
                           
xi = each value

𝜇 = mean of all values

𝑛 = number of values